openapi: 3.0.0
info:
  title: API de Juegos
  description: API para manejar juegos, incluyendo creación, edición, eliminación y obtención de información.
  version: 1.0.0
servers:
  - url: http://localhost:3000
    description: Servidor local

paths:
  /juegos:
    get:
      summary: Obtener juegos
      description: Obtiene una lista de juegos con soporte para paginación y búsqueda.
      parameters:
        - in: query
          name: limit
          schema:
            type: integer
          description: Límite de resultados a devolver
        - in: query
          name: next
          schema:
            type: string
          description: ID del juego a partir del cual obtener los siguientes resultados
        - in: query
          name: prev
          schema:
            type: string
          description: ID del juego a partir del cual obtener los resultados anteriores
        - in: query
          name: search
          schema:
            type: string
          description: Término de búsqueda para buscar juegos por nombre
      responses:
        200:
          description: Lista de juegos obtenida con éxito
          content:
            application/json:
              schema:
                type: object
                properties:
                  results:
                    type: array
                    items:
                      $ref: '#/components/schemas/Game'
                  next:
                    type: string
                    nullable: true
                  prev:
                    type: string
                    nullable: true
        400:
          description: Error al buscar juegos
        500:
          description: Error interno del servidor

  /juegos/{name}:
    get:
      summary: Obtener juego por nombre
      description: Obtiene un juego por su nombre.
      parameters:
        - in: path
          name: name
          required: true
          schema:
            type: string
          description: Nombre del juego
      responses:
        200:
          description: Juego obtenido con éxito
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Game'
        404:
          description: Juego no encontrado
        500:
          description: Error interno del servidor

  /juegos/{id}:
    delete:
      summary: Eliminar juego por ID
      description: Elimina un juego por su ID.
      parameters:
        - in: path
          name: id
          required: true
          schema:
            type: string
          description: ID del juego
      responses:
        200:
          description: Juego eliminado con éxito
        404:
          description: Juego no encontrado
        500:
          description: Error interno del servidor

  /new_game:
    post:
      summary: Crear un nuevo juego
      description: Crea un nuevo juego con los datos proporcionados.
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Game'
      responses:
        201:
          description: Juego creado con éxito
        400:
          description: Error en los datos proporcionados
        500:
          description: Error interno del servidor

  /noticias:
    get:
      summary: Obtener noticias de juegos
      description: Obtiene noticias de juegos desde una API externa.
      parameters:
        - in: query
          name: count
          schema:
            type: integer
          description: Número de noticias a obtener
      responses:
        200:
          description: Noticias obtenidas con éxito
          content:
            application/xml:
              schema:
                type: string
                format: xml
        500:
          description: Error al obtener los datos de la API externa

  /edit_juego/{id}:
    get:
      summary: Obtener información de un juego por ID para editar
      description: Obtiene la información de un juego por su ID.
      parameters:
        - in: path
          name: id
          required: true
          schema:
            type: string
          description: ID del juego
      responses:
        200:
          description: Información del juego obtenida con éxito
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Game'
        404:
          description: Juego no encontrado
        500:
          description: Error al obtener el juego

    post:
      summary: Guardar cambios en la información de un juego
      description: Guarda los cambios en la información de un juego.
      parameters:
        - in: path
          name: id
          required: true
          schema:
            type: string
          description: ID del juego
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Game'
      responses:
        200:
          description: Juego editado con éxito
        404:
          description: Juego no encontrado para actualizar
        500:
          description: Error al actualizar el juego

  /info_juegos/{id}:
    get:
      summary: Obtener información de un juego por ID
      description: Obtiene la información de un juego por su ID.
      parameters:
        - in: path
          name: id
          required: true
          schema:
            type: string
          description: ID del juego
      responses:
        200:
          description: Información del juego obtenida con éxito
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Game'
        404:
          description: Juego no encontrado
        500:
          description: Error al obtener el juego

components:
  schemas:
    Game:
      type: object
      required:
        - _id
        - header_image
        - short_description
        - price
        - release_date
        - categories
        - genres

      properties:
        _id:
          type: string
          description: ID del juego
        header_image:
          type: string
          description: URL de la imagen del encabezado del juego
        name:
          type: string
          description: Nombre del juego
        short_description:
          type: string
          description: Descripción breve del juego
        price:
          type: number
          description: Precio del juego
        release_date:
          type: string
          format: date
          description: Fecha de lanzamiento del juego
        categories:
          type: array
          items:
            type: string
          description: Categorías del juego
        genres:
          type: array
          items:
            type: string
          description: Géneros del juego
